"""
generate signed urls or cookies for AWS CloudFront

pip install botocore rsa requests
"""
from datetime import datetime, timedelta
import functools
from urllib.parse import urlsplit

from botocore.signers import CloudFrontSigner
import requests
import rsa
import click


class CloudFrontUtil:
    def __init__(self, private_key_path: str, key_id: str):
        """
        :param private_key_path: str, the path of private key which generated by openssl command line
        :param key_id: str, CloudFront -> Key management -> Public keys
        """
        self.key_id = key_id

        with open(private_key_path, 'rb') as fp:
            priv_key = rsa.PrivateKey.load_pkcs1(fp.read())

        # NOTE: CloudFront use RSA-SHA1 for signing URLs or cookies
        self.rsa_signer = functools.partial(
            rsa.sign, priv_key=priv_key, hash_method='SHA-1'
        )
        self.cf_signer = CloudFrontSigner(key_id, self.rsa_signer)

    def generate_presigned_url(self, url: str, expire_at: datetime) -> str:
        # Create a signed url that will be valid until the specfic expiry date
        # provided using a canned policy.
        return self.cf_signer.generate_presigned_url(url, date_less_than=expire_at)

    def generate_signed_cookies(self, url: str, expire_at: datetime) -> str:
        policy = self.cf_signer.build_policy(url, expire_at).encode('utf8')
        print(policy)
        policy_64 = self.cf_signer._url_b64encode(policy).decode('utf8')

        signature = self.rsa_signer(policy)
        signature_64 = self.cf_signer._url_b64encode(signature).decode('utf8')
        return {
            "CloudFront-Policy": policy_64,
            "CloudFront-Signature": signature_64,
            "CloudFront-Key-Pair-Id": self.key_id,
        }


@click.command()
@click.option("--url", default="https://d2gkxt2zllryfn.cloudfront.net/*")
@click.option("--key", type=click.Path(exists=True, file_okay=True, dir_okay=False))
@click.option("--key_id", default="AvianData")
@click.option("--expire_at", type=click.DateTime(formats=['%Y-%m-%d %H:%M:%S']))
def generate_cookie(url="https://d2gkxt2zllryfn.cloudfront.net/*",key="avian.key",key_id="AvianData", expire_at=None ):
    """
    """
    if not expire_at:
        expire_at = datetime.now() + timedelta(days=10)
    util = CloudFrontUtil(key, key_id)
    signed_cookies = util.generate_signed_cookies(url,expire_at)
    print("\n".join([f"document.cookie='{k}={signed_cookies[k]}'" for k in signed_cookies]))
    print(util.generate_presigned_url(url, expire_at))
if __name__ == '__main__':
    generate_cookie()
